//! # zkml-verifier
//!
//! Soroban smart contract that verifies Groth16 proofs of ML inference.
//!
//! This contract provides on-chain verification of zero-knowledge proofs
//! generated by the off-chain prover. It leverages the BN254 elliptic curve
//! host functions introduced in Stellar Protocol 25 (X-Ray) via CAP-0074,
//! and checks Poseidon model commitments (CAP-0075) computed off-chain.
//!
//! # Contract Interface
//!
//! - `initialize`: Register the model commitment.
//! - `verify_inference`: Accept a Groth16 proof and public inputs, verify
//!   correctness, record the result, and emit an event.
//! - `get_result`: Query the last verified inference result.
//! - `get_model_hash`: Query the registered model commitment.
//! - `get_verification_count`: Query how many proofs have been verified.

#![no_std]

// The contract is no_std; its tests are not. The golden fixture lives on disk
// and is read with std::fs, which keeps a real proof in the repository instead
// of a wall of hex constants in this file.
#[cfg(test)]
extern crate std;

use soroban_sdk::crypto::bn254::{Bn254Fr, Bn254G1Affine, Bn254G2Affine};
use soroban_sdk::{
    contract, contracterror, contractimpl, contracttype, log, symbol_short, vec, Address, Bytes,
    Env, Symbol, Vec, U256,
};

use zkml_common::journal::JournalV1;
use zkml_common::risc0::{Digest, SEAL_LEN};

// Storage keys
const MODEL_HASH: Symbol = symbol_short!("mdl_hash");
/// RISC Zero image id, control root, BN254 control id and seal selector.
const RISC0_CFG: Symbol = symbol_short!("r0_cfg");
/// RISC Zero's universal Groth16 verifying key. Separate from [`VERIFICATION_KEY`]
/// because a receipt has five public inputs where the native-circuit path has
/// four, so the two keys have different `ic` lengths and are not interchangeable.
const RISC0_VK: Symbol = symbol_short!("r0_vk");
const VERIFICATION_KEY: Symbol = symbol_short!("vk");
const LAST_RESULT: Symbol = symbol_short!("lst_res");
const INITIALIZED: Symbol = symbol_short!("init");
const VERIFY_CNT: Symbol = symbol_short!("vrf_cnt");
const NULLIFIER_PREFIX: Symbol = symbol_short!("nullifier");
const ADMIN: Symbol = symbol_short!("admin");
const PAUSED: Symbol = symbol_short!("paused");

/// Ledgers per day on Stellar (~5s per ledger).
const DAY_IN_LEDGERS: u32 = 17_280;

/// Renew instance TTL when remaining lifetime falls below 30 days.
/// A verifier used at least monthly stays live without an external keeper.
const INSTANCE_TTL_THRESHOLD: u32 = 30 * DAY_IN_LEDGERS;

/// Extend instance TTL to 120 days when the threshold is crossed.
/// Matches the typical persistent rent floor and stays under the ~180-day network max.
const INSTANCE_TTL_EXTEND_TO: u32 = 120 * DAY_IN_LEDGERS;

/// Contract interface version, bumped on breaking interface changes.
pub const VERSION: u32 = 6;

/// Minimum protocol version required for BN254 host functions (CAP-0074).
pub const MIN_PROTOCOL_VERSION: u32 = 25;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum VerificationError {
    ContractNotInitialized = 1,
    PublicInputsTooShort = 2,
    MalformedProofA = 3,
    MalformedProofB = 4,
    MalformedProofC = 5,
    MalformedVerificationKey = 6,
    VerificationFailed = 7,
    InvalidPublicInputLength = 8,
    VerificationKeyLengthMismatch = 9,
    ProofAlreadyUsed = 10,
    /// The seal is not [`zkml_common::risc0::SEAL_LEN`] bytes.
    MalformedSeal = 11,
    /// The seal was produced for a different RISC Zero version.
    UnknownSelector = 12,
    /// The journal is not the 96-byte `JournalV1` layout, or its magic or
    /// version do not match what this contract was built for.
    MalformedJournal = 13,
    /// `set_risc0_config` has not been called, so there is nothing to verify
    /// a receipt against.
    Risc0NotConfigured = 14,
}

/// On-chain representation of BN254 Groth16 verification key.
#[contracttype]
#[derive(Clone, Debug)]
pub struct VerificationKey {
    /// G1 point alpha (64 bytes)
    pub alpha: Bytes,
    /// G2 point beta (128 bytes)
    pub beta: Bytes,
    /// G2 point gamma (128 bytes)
    pub gamma: Bytes,
    /// G2 point delta (128 bytes)
    pub delta: Bytes,
    /// IC points array (each G1 point, 64 bytes)
    pub ic: Vec<Bytes>,
}

/// What a RISC Zero receipt is verified against.
///
/// Every field comes from `zkml-prover export-vk`, and every one of them is
/// pinned to a RISC Zero version and a guest build: change either and these
/// must be re-exported, or nothing will verify.
#[contracttype]
#[derive(Clone, Debug)]
pub struct Risc0Config {
    /// Which guest program must have produced the journal.
    pub image_id: Bytes,
    /// RISC Zero's recursion control root.
    pub control_root: Bytes,
    /// RISC Zero's BN254 control id.
    pub bn254_control_id: Bytes,
    /// The four bytes a seal must start with, identifying the verifying key.
    pub selector: Bytes,
}

/// On-chain record of a verified inference result.
#[contracttype]
#[derive(Clone, Debug)]
pub struct InferenceRecord {
    /// Poseidon commitment to the model that produced this result.
    pub model_hash: Bytes,
    /// The inference output value (raw score).
    pub output: Bytes,
    /// The class label decision (binary decision or argmax index).
    pub class_label: i64,
    /// Ledger sequence number at verification time.
    pub verified_at: u32,
}

#[contract]
pub struct ZkmlVerifierContract;

#[contractimpl]
impl ZkmlVerifierContract {
    /// Register what RISC Zero receipts are verified against.
    ///
    /// Run `zkml-prover export-vk --format soroban-args` to produce these. The
    /// values are pinned to a RISC Zero version and a guest build, so they must
    /// be re-exported whenever either changes.
    pub fn set_risc0_config(env: Env, config: Risc0Config) {
        let admin: Address = env
            .storage()
            .instance()
            .get(&ADMIN)
            .expect("contract is not initialized");
        admin.require_auth();

        // Catching a wrong length here costs nothing; catching it during a
        // pairing check costs a failed transaction and says nothing useful.
        if config.image_id.len() != 32
            || config.control_root.len() != 32
            || config.bn254_control_id.len() != 32
            || config.selector.len() != 4
        {
            panic!("risc0 config fields have the wrong length");
        }
        env.storage().instance().set(&RISC0_CFG, &config);
        Self::bump_instance_ttl(&env);
        log!(&env, "RISC Zero config updated by admin");
    }

    /// The registered RISC Zero configuration.
    pub fn get_risc0_config(env: Env) -> Risc0Config {
        env.storage()
            .instance()
            .get(&RISC0_CFG)
            .expect("risc0 config has not been set")
    }

    /// Register RISC Zero's universal Groth16 verifying key.
    ///
    /// This is not the key used by [`Self::verify_inference`]. A receipt has
    /// five public inputs, so this key carries six `ic` points against the
    /// other's five, and using one where the other belongs fails every proof.
    pub fn set_risc0_vk(env: Env, vk: VerificationKey) {
        let admin: Address = env
            .storage()
            .instance()
            .get(&ADMIN)
            .expect("contract is not initialized");
        admin.require_auth();
        if vk.ic.len() != 6 {
            panic!("a RISC Zero verifying key has six ic points");
        }
        env.storage().instance().set(&RISC0_VK, &vk);
        Self::bump_instance_ttl(&env);
        log!(&env, "RISC Zero verifying key updated by admin");
    }

    /// Verify a Groth16 receipt produced by `zkml-prover prove --groth16`.
    ///
    /// Takes the seal and the journal exactly as the bundle carries them. The
    /// journal is not a public input of the proof: it is bound through the
    /// claim digest, which this recomputes, so a journal that does not match
    /// the proof cannot pass.
    ///
    /// Checks run cheapest first. Length, selector, journal layout and the
    /// registered model hash all fail before the pairing, which is the only
    /// expensive step.
    pub fn verify_receipt(env: Env, seal: Bytes, journal: Bytes) -> Result<(), VerificationError> {
        if !env.storage().instance().has(&INITIALIZED) {
            return Err(VerificationError::ContractNotInitialized);
        }
        let paused: bool = env.storage().instance().get(&PAUSED).unwrap_or(false);
        if paused {
            return Err(VerificationError::VerificationFailed);
        }

        let config: Risc0Config = env
            .storage()
            .instance()
            .get(&RISC0_CFG)
            .ok_or(VerificationError::Risc0NotConfigured)?;
        let vk: VerificationKey = env
            .storage()
            .instance()
            .get(&RISC0_VK)
            .ok_or(VerificationError::Risc0NotConfigured)?;

        Self::check_seal(&seal, &config)?;
        let journal_v1 = Self::decode_journal(&journal)?;

        // The result must come from the model this contract was told about.
        let stored_model_hash: Bytes = env
            .storage()
            .instance()
            .get(&MODEL_HASH)
            .ok_or(VerificationError::ContractNotInitialized)?;
        if Bytes::from_slice(&env, &journal_v1.model_hash) != stored_model_hash {
            return Err(VerificationError::VerificationFailed);
        }

        // Rebuild what the proof actually commits to.
        let claim = Self::claim_digest_inner(&env, &config.image_id, &journal)?;
        let mut control_root = [0u8; 32];
        config.control_root.copy_into_slice(&mut control_root);
        let mut bn254_control_id = [0u8; 32];
        config
            .bn254_control_id
            .copy_into_slice(&mut bn254_control_id);
        let inputs =
            zkml_common::risc0::groth16_public_inputs(&control_root, &claim, &bn254_control_id);

        let bn254 = env.crypto().bn254();
        let alpha_g1 = Self::deserialize_vk_alpha(&env, &vk.alpha)?;
        let beta_g2 = Self::deserialize_vk_g2(&env, &vk.beta)?;
        let gamma_g2 = Self::deserialize_vk_g2(&env, &vk.gamma)?;
        let delta_g2 = Self::deserialize_vk_g2(&env, &vk.delta)?;
        let l = Self::compute_l_be(&env, &vk, &inputs)?;

        // The seal carries the points in the layout Soroban reads, so they are
        // sliced out and passed through unchanged: G1 as be(x) || be(y), G2 as
        // be(x.c1) || be(x.c0) || be(y.c1) || be(y.c0).
        let proof_a = Self::deserialize_g1(&env, &seal.slice(4..68))?;
        let proof_b = Self::deserialize_g2(&env, &seal.slice(68..196))?;
        let proof_c = Self::deserialize_g1(&env, &seal.slice(196..260))?;

        let neg_a = -proof_a;
        let vp1 = vec![&env, neg_a, alpha_g1, l, proof_c];
        let vp2 = vec![&env, proof_b, beta_g2, gamma_g2, delta_g2];
        if !bn254.pairing_check(vp1, vp2) {
            return Err(VerificationError::VerificationFailed);
        }

        // Replay protection keys on the same 80 bytes the native-circuit path
        // uses, so the same inference cannot be recorded twice by arriving
        // through a different route.
        let public_inputs = Bytes::from_slice(&env, &journal_v1.public_inputs_bytes());
        let nullifier = Self::derive_nullifier(&env, &public_inputs);
        let nullifier_key = (NULLIFIER_PREFIX, nullifier.clone());
        if env.storage().persistent().has(&nullifier_key) {
            return Err(VerificationError::ProofAlreadyUsed);
        }
        let ttl_ledgers = env.storage().max_ttl();
        env.storage().persistent().set(&nullifier_key, &true);
        env.storage()
            .persistent()
            .extend_ttl(&nullifier_key, ttl_ledgers, ttl_ledgers);

        let record = InferenceRecord {
            model_hash: Bytes::from_slice(&env, &journal_v1.model_hash),
            output: Bytes::from_slice(&env, &journal_v1.output.to_le_bytes()),
            class_label: journal_v1.class_label,
            verified_at: env.ledger().sequence(),
        };
        env.storage().instance().set(&LAST_RESULT, &record);

        let count: u32 = env.storage().instance().get(&VERIFY_CNT).unwrap_or(0);
        env.storage().instance().set(&VERIFY_CNT, &(count + 1));
        Self::bump_instance_ttl(&env);
        Self::emit_verified_event(&env, &record);

        Ok(())
    }

    /// Recompute the claim digest a Groth16 receipt commits to.
    ///
    /// The journal is not a public input of the proof: it reaches the proof
    /// only through this digest, which also binds the image id. A verifier that
    /// skipped this would be checking that *some* program produced *some*
    /// output.
    ///
    /// Hashing goes through `env.crypto().sha256()`, a host function, rather
    /// than a SHA-256 compiled into this WASM. The arithmetic itself is shared
    /// with the prover so the two cannot drift.
    pub fn claim_digest(env: Env, image_id: Bytes, journal: Bytes) -> Bytes {
        let digest = Self::claim_digest_inner(&env, &image_id, &journal)
            .unwrap_or_else(|_| panic!("image id must be 32 bytes"));
        Bytes::from_slice(&env, &digest)
    }

    /// Initialize the contract with a model commitment and Groth16 verification key. Call exactly once.
    /// Initialize the contract with a model commitment and verification key. Call exactly once.
    pub fn initialize(env: Env, admin: Address, model_hash: Bytes, vk: VerificationKey) {
        admin.require_auth();
        if env.storage().instance().has(&INITIALIZED) {
            panic!("contract is already initialized");
        }
        env.storage().instance().set(&ADMIN, &admin);
        env.storage().instance().set(&MODEL_HASH, &model_hash);
        env.storage().instance().set(&VERIFICATION_KEY, &vk);
        env.storage().instance().set(&VERIFY_CNT, &0u32);
        env.storage().instance().set(&PAUSED, &false);
        env.storage().instance().set(&INITIALIZED, &true);
        Self::bump_instance_ttl(&env);
        log!(
            &env,
            "ZKML verifier initialized with model commitment and verification key"
        );
    }

    /// Verify a Groth16 proof of ML inference.
    ///
    /// `public_inputs` is the concatenation of the 32-byte model commitment,
    /// the 32-byte input commitment, and N * 8-byte output scalars (for multi-class output).
    pub fn verify_inference(
        env: Env,
        proof_a: Bytes,
        proof_b: Bytes,
        proof_c: Bytes,
        public_inputs: Bytes,
    ) -> Result<(), VerificationError> {
        if !env.storage().instance().has(&INITIALIZED) {
            return Err(VerificationError::ContractNotInitialized);
        }

        let paused: bool = env.storage().instance().get(&PAUSED).unwrap_or(false);
        if paused {
            return Err(VerificationError::VerificationFailed);
        }

        // Deserialize proof points
        let proof_a_g1 = Self::deserialize_g1(&env, &proof_a)?;
        let proof_b_g2 = Self::deserialize_g2(&env, &proof_b)?;
        let proof_c_g1 = Self::deserialize_g1(&env, &proof_c)?;

        // Get verification key
        let vk: VerificationKey = env
            .storage()
            .instance()
            .get(&VERIFICATION_KEY)
            .ok_or(VerificationError::ContractNotInitialized)?;

        // Parse public inputs with canonical length validation
        let parsed_inputs = Self::parse_public_inputs(&env, &public_inputs)?;

        // Verify model hash matches stored commitment
        let model_hash = parsed_inputs.get(0).unwrap();
        let stored_model_hash: Bytes = env
            .storage()
            .instance()
            .get(&MODEL_HASH)
            .ok_or(VerificationError::ContractNotInitialized)?;
        if model_hash != stored_model_hash {
            return Err(VerificationError::VerificationFailed);
        }

        // Convert public inputs to field elements for L computation
        let bn254 = env.crypto().bn254();

        // Deserialize VK fields to BN254 types
        let alpha_g1 = Self::deserialize_vk_alpha(&env, &vk.alpha)?;
        let beta_g2 = Self::deserialize_vk_g2(&env, &vk.beta)?;
        let gamma_g2 = Self::deserialize_vk_g2(&env, &vk.gamma)?;
        let delta_g2 = Self::deserialize_vk_g2(&env, &vk.delta)?;

        // L = sum(public_input_i * vk_ic_i)
        // Note: In Groth16, IC[0] is the constant term, and public inputs start at index 1
        // Compute L = ic[0] + sum(scalar_i * ic[i]) using generic loop
        let l = Self::compute_l(&env, &vk, &parsed_inputs)?;

        // Pairing check: e(A, B) == e(alpha, beta) * e(L, gamma) * e(C, delta)
        // Equivalent to: e(-A, B) * e(alpha, beta) * e(L, gamma) * e(C, delta) == 1
        let neg_a = -proof_a_g1;
        let vp1 = vec![&env, neg_a, alpha_g1, l, proof_c_g1];
        let vp2 = vec![&env, proof_b_g2, beta_g2, gamma_g2, delta_g2];

        if !bn254.pairing_check(vp1, vp2) {
            return Err(VerificationError::VerificationFailed);
        }

        // Derive nullifier from public inputs to prevent replay attacks
        let nullifier = Self::derive_nullifier(&env, &public_inputs);

        // Check if this proof has already been used
        let nullifier_key = (NULLIFIER_PREFIX, nullifier.clone());
        if env.storage().persistent().has(&nullifier_key) {
            return Err(VerificationError::ProofAlreadyUsed);
        }

        // Store nullifier in persistent storage with TTL bump
        // Use the network maximum persistent TTL (env.storage().max_ttl())
        // This ensures nullifiers persist for the maximum allowed duration
        let ttl_ledgers = env.storage().max_ttl();
        env.storage().persistent().set(&nullifier_key, &true);
        env.storage()
            .persistent()
            .extend_ttl(&nullifier_key, ttl_ledgers, ttl_ledgers);

        // Verification succeeded - record result
        // Output starts after model_hash (32) and input_hash (32) = byte 64
        // Output is 8 bytes, class_label is next 8 bytes
        let output = public_inputs.slice(64..72);
        let class_label_bytes = public_inputs.slice(72..80);
        let class_label = Self::bytes_to_i64(&class_label_bytes);

        let record = InferenceRecord {
            model_hash: model_hash.clone(),
            output,
            class_label,
            verified_at: env.ledger().sequence(),
        };
        env.storage().instance().set(&LAST_RESULT, &record);

        let count: u32 = env.storage().instance().get(&VERIFY_CNT).unwrap_or(0);
        env.storage().instance().set(&VERIFY_CNT, &(count + 1));
        Self::bump_instance_ttl(&env);

        Self::emit_verified_event(&env, &record);

        Ok(())
    }

    /// Renew instance storage TTL when remaining lifetime is below the threshold.
    ///
    /// `extend_ttl` is a no-op unless the current TTL is below
    /// [`INSTANCE_TTL_THRESHOLD`]; then it is set to [`INSTANCE_TTL_EXTEND_TO`].
    fn bump_instance_ttl(env: &Env) {
        env.storage()
            .instance()
            .extend_ttl(INSTANCE_TTL_THRESHOLD, INSTANCE_TTL_EXTEND_TO);
    }

    /// Publish the `verified` event enriched with `model_hash` (a topic, so
    /// indexers can filter per model) and `output` (data), alongside the ledger
    /// sequence number (`verified_at`).
    fn emit_verified_event(env: &Env, record: &InferenceRecord) {
        #[allow(deprecated)]
        env.events().publish(
            (symbol_short!("verified"), record.model_hash.clone()),
            (record.verified_at, record.output.clone()),
        );
    }

    /// Deserialize a G1 point from 64 bytes (Ethereum-compatible format).
    fn deserialize_g1(env: &Env, bytes: &Bytes) -> Result<Bn254G1Affine, VerificationError> {
        if bytes.len() != 64 {
            return Err(VerificationError::MalformedProofA);
        }
        let mut array = [0u8; 64];
        bytes.copy_into_slice(&mut array);
        Ok(Bn254G1Affine::from_array(env, &array))
    }

    /// Deserialize a G2 point from 128 bytes (Ethereum-compatible format).
    /// A big-endian 32-byte value as a field element.
    ///
    /// Deliberately not [`Self::bytes_to_fr`], which reads little-endian. The
    /// native-circuit path feeds little-endian `i64` fields; RISC Zero's five
    /// public inputs are big-endian, and reading one as the other produces a
    /// valid-looking scalar that fails every pairing with nothing to point at.
    fn bytes_to_fr_be(env: &Env, bytes: &[u8; 32]) -> Bn254Fr {
        let buf = Bytes::from_slice(env, bytes);
        U256::from_be_bytes(env, &buf).into()
    }

    /// `L = ic[0] + sum(input_i * ic[i + 1])` over big-endian scalars.
    fn compute_l_be(
        env: &Env,
        vk: &VerificationKey,
        inputs: &[zkml_common::risc0::Digest; 5],
    ) -> Result<Bn254G1Affine, VerificationError> {
        if vk.ic.len() as usize != inputs.len() + 1 {
            return Err(VerificationError::VerificationKeyLengthMismatch);
        }
        let bn254 = env.crypto().bn254();
        let ic0 = vk
            .ic
            .get(0)
            .ok_or(VerificationError::MalformedVerificationKey)?;
        let mut l = Self::deserialize_vk_ic(env, &ic0)?;
        for (i, input) in inputs.iter().enumerate() {
            let ic_bytes = vk
                .ic
                .get(i as u32 + 1)
                .ok_or(VerificationError::MalformedVerificationKey)?;
            let ic_point = Self::deserialize_vk_ic(env, &ic_bytes)?;
            let term = bn254.g1_mul(&ic_point, &Self::bytes_to_fr_be(env, input));
            l = bn254.g1_add(&l, &term);
        }
        Ok(l)
    }

    /// SHA-256 through the Soroban host, shaped for `zkml_common::risc0`.
    ///
    /// The host returns a `BytesN<32>`; the digest arithmetic works on
    /// `[u8; 32]`, so this is the only glue needed for the contract and the
    /// prover to compute identical digests.
    fn host_sha256(env: &Env) -> impl Fn(&[u8]) -> Digest + Copy + '_ {
        move |bytes: &[u8]| -> Digest {
            let buf = Bytes::from_slice(env, bytes);
            env.crypto().sha256(&buf).to_array()
        }
    }

    /// Reconstruct the receipt claim digest from an image id and a journal.
    fn claim_digest_inner(
        env: &Env,
        image_id: &Bytes,
        journal: &Bytes,
    ) -> Result<Digest, VerificationError> {
        if image_id.len() != 32 {
            return Err(VerificationError::MalformedVerificationKey);
        }
        let mut id = [0u8; 32];
        image_id.copy_into_slice(&mut id);

        let journal_bytes = Self::journal_to_vec(journal);
        Ok(zkml_common::risc0::receipt_claim_ok_digest(
            Self::host_sha256(env),
            &id,
            &journal_bytes,
        ))
    }

    /// Copy a journal out of host memory into a fixed buffer.
    ///
    /// A `JournalV1` is always 96 bytes, so this needs no allocator.
    fn journal_to_vec(journal: &Bytes) -> [u8; zkml_common::journal::JOURNAL_V1_LEN] {
        let mut buf = [0u8; zkml_common::journal::JOURNAL_V1_LEN];
        let n = core::cmp::min(journal.len() as usize, buf.len());
        for i in 0..n {
            buf[i] = journal.get(i as u32).unwrap_or(0);
        }
        buf
    }

    /// Decode a journal, rejecting anything this contract was not built for.
    fn decode_journal(journal: &Bytes) -> Result<JournalV1, VerificationError> {
        if journal.len() as usize != zkml_common::journal::JOURNAL_V1_LEN {
            return Err(VerificationError::MalformedJournal);
        }
        let buf = Self::journal_to_vec(journal);
        JournalV1::decode(&buf).map_err(|_| VerificationError::MalformedJournal)
    }

    /// Check a seal's length and that it was made for the registered verifying
    /// key, before spending anything on a pairing that cannot succeed.
    fn check_seal(seal: &Bytes, config: &Risc0Config) -> Result<(), VerificationError> {
        if seal.len() as usize != SEAL_LEN {
            return Err(VerificationError::MalformedSeal);
        }
        for i in 0..4u32 {
            if seal.get(i) != config.selector.get(i) {
                return Err(VerificationError::UnknownSelector);
            }
        }
        Ok(())
    }

    fn deserialize_g2(env: &Env, bytes: &Bytes) -> Result<Bn254G2Affine, VerificationError> {
        if bytes.len() != 128 {
            return Err(VerificationError::MalformedProofB);
        }
        let mut array = [0u8; 128];
        bytes.copy_into_slice(&mut array);
        Ok(Bn254G2Affine::from_array(env, &array))
    }

    /// Deserialize VK alpha (G1) from Bytes.
    fn deserialize_vk_alpha(env: &Env, bytes: &Bytes) -> Result<Bn254G1Affine, VerificationError> {
        if bytes.len() != 64 {
            return Err(VerificationError::MalformedVerificationKey);
        }
        let mut array = [0u8; 64];
        bytes.copy_into_slice(&mut array);
        Ok(Bn254G1Affine::from_array(env, &array))
    }

    /// Deserialize VK beta/gamma/delta (G2) from Bytes.
    fn deserialize_vk_g2(env: &Env, bytes: &Bytes) -> Result<Bn254G2Affine, VerificationError> {
        if bytes.len() != 128 {
            return Err(VerificationError::MalformedVerificationKey);
        }
        let mut array = [0u8; 128];
        bytes.copy_into_slice(&mut array);
        Ok(Bn254G2Affine::from_array(env, &array))
    }

    /// Deserialize VK IC element (G1) from Bytes.
    fn deserialize_vk_ic(env: &Env, bytes: &Bytes) -> Result<Bn254G1Affine, VerificationError> {
        if bytes.len() != 64 {
            return Err(VerificationError::MalformedVerificationKey);
        }
        let mut array = [0u8; 64];
        bytes.copy_into_slice(&mut array);
        Ok(Bn254G1Affine::from_array(env, &array))
    }

    /// Convert little-endian public-input bytes to a Bn254Fr scalar field element.
    ///
    /// Public inputs are little-endian: `model_hash` and `input_hash` come from
    /// `Commitment` (`poseidon_commit` emits `to_bytes_le`, see
    /// docs/concepts/commitments.md) and the output is `i64::to_le_bytes`. soroban's
    /// `U256` only parses big-endian, so the bytes are zero-extended to 32 (low
    /// order first) and reversed into big-endian before parsing. Values >= the
    /// BN254 scalar field order r are reduced by the Bn254Fr constructor.
    /// If bytes.len() > 32, only the low-order 32 bytes are used.
    fn bytes_to_fr(env: &Env, bytes: &Bytes) -> Bn254Fr {
        let mut le = [0u8; 32];
        let len = bytes.len().min(32);
        // Little-endian: low-order bytes first, zero-padded on the right.
        let src = bytes.slice(0..len);
        src.copy_into_slice(&mut le[..len as usize]);
        // soroban U256 parses big-endian only, so reverse into a big-endian buffer.
        let mut be = [0u8; 32];
        for i in 0..32 {
            be[i] = le[31 - i];
        }
        let bytes_ref = Bytes::from_slice(env, &be);
        U256::from_be_bytes(env, &bytes_ref).into()
    }

    /// Convert little-endian bytes to i64.
    fn bytes_to_i64(bytes: &Bytes) -> i64 {
        let mut arr = [0u8; 8];
        let len = bytes.len().min(8);
        bytes
            .slice(0..len)
            .copy_into_slice(&mut arr[..len as usize]);
        i64::from_le_bytes(arr)
    }

    /// Parse public inputs into a vector of byte slices with canonical length validation.
    ///
    /// Public input layout:
    /// - model_hash: 32 bytes (canonical Poseidon commitment)
    /// - input_hash: 32 bytes (canonical Poseidon commitment)
    /// - output: 8 bytes (canonical i64 in little-endian)
    /// - class_label: 8 bytes (canonical i64 in little-endian)
    ///
    /// Returns an error if any field has non-canonical length.
    fn parse_public_inputs(
        env: &Env,
        public_inputs: &Bytes,
    ) -> Result<Vec<Bytes>, VerificationError> {
        let mut parsed = Vec::new(env);
        let mut offset = 0u32;

        // Parse model_hash (must be exactly 32 bytes)
        if public_inputs.len() < offset + 32 {
            return Err(VerificationError::PublicInputsTooShort);
        }
        let model_hash = public_inputs.slice(offset..(offset + 32));
        if model_hash.len() != 32 {
            return Err(VerificationError::InvalidPublicInputLength);
        }
        parsed.push_back(model_hash);
        offset += 32;

        // Parse input_hash (must be exactly 32 bytes)
        if public_inputs.len() < offset + 32 {
            return Err(VerificationError::PublicInputsTooShort);
        }
        let input_hash = public_inputs.slice(offset..(offset + 32));
        if input_hash.len() != 32 {
            return Err(VerificationError::InvalidPublicInputLength);
        }
        parsed.push_back(input_hash);
        offset += 32;

        // Parse output (must be exactly 8 bytes for canonical i64)
        if public_inputs.len() < offset + 8 {
            return Err(VerificationError::PublicInputsTooShort);
        }
        let output = public_inputs.slice(offset..(offset + 8));
        if output.len() != 8 {
            return Err(VerificationError::InvalidPublicInputLength);
        }
        parsed.push_back(output);
        offset += 8;

        // Parse class_label (must be exactly 8 bytes for canonical i64)
        if public_inputs.len() < offset + 8 {
            return Err(VerificationError::PublicInputsTooShort);
        }
        let class_label = public_inputs.slice(offset..(offset + 8));
        if class_label.len() != 8 {
            return Err(VerificationError::InvalidPublicInputLength);
        }
        parsed.push_back(class_label);
        offset += 8;

        // Ensure no extra data
        if offset != public_inputs.len() {
            return Err(VerificationError::InvalidPublicInputLength);
        }

        Ok(parsed)
    }

    /// Compute L = ic[0] + sum(scalar_i * ic[i]) for i from 1 to n.
    ///
    /// Validates that vk.ic.len() == n + 1 where n is the number of public input scalars.
    fn compute_l(
        env: &Env,
        vk: &VerificationKey,
        public_input_scalars: &Vec<Bytes>,
    ) -> Result<Bn254G1Affine, VerificationError> {
        let bn254 = env.crypto().bn254();
        let num_scalars = public_input_scalars.len();

        // Validate VK IC length matches number of scalars + 1 (for ic[0])
        if vk.ic.len() != num_scalars + 1 {
            return Err(VerificationError::VerificationKeyLengthMismatch);
        }

        // Start with ic[0]
        let ic0_bytes = vk
            .ic
            .get(0)
            .ok_or(VerificationError::MalformedVerificationKey)?;
        let mut l = Self::deserialize_vk_ic(env, &ic0_bytes)?;

        // Add each scalar * ic[i] term
        for i in 0..num_scalars {
            let scalar_bytes = public_input_scalars.get(i).unwrap();
            let scalar = Self::bytes_to_fr(env, &scalar_bytes);
            let ic_bytes = vk
                .ic
                .get(i + 1)
                .ok_or(VerificationError::MalformedVerificationKey)?;
            let ic_point = Self::deserialize_vk_ic(env, &ic_bytes)?;
            let term = bn254.g1_mul(&ic_point, &scalar);
            l = bn254.g1_add(&l, &term);
        }

        Ok(l)
    }

    /// Derive a nullifier from the public inputs to prevent proof replay attacks.
    ///
    /// The nullifier is computed as SHA256(public_inputs), which includes:
    /// - model_hash (32 bytes)
    /// - input_hash (32 bytes)  
    /// - output scalars (N * 8 bytes)
    ///
    /// This ensures that each unique (model, input, output) tuple can only be verified once.
    fn derive_nullifier(env: &Env, public_inputs: &Bytes) -> Bytes {
        env.crypto().sha256(public_inputs).into()
    }

    /// Retrieve the last verified inference result.
    pub fn get_result(env: Env) -> InferenceRecord {
        env.storage()
            .instance()
            .get(&LAST_RESULT)
            .expect("no inference result has been recorded yet")
    }

    /// Retrieve the registered model commitment.
    pub fn get_model_hash(env: Env) -> Bytes {
        env.storage()
            .instance()
            .get(&MODEL_HASH)
            .expect("contract is not initialized")
    }

    /// Retrieve the number of verified proofs so far.
    pub fn get_verification_count(env: Env) -> u32 {
        env.storage().instance().get(&VERIFY_CNT).unwrap_or(0)
    }

    /// Return the contract interface version.
    pub fn version(_env: Env) -> u32 {
        VERSION
    }

    /// Set a new verification key. Only callable by admin.
    pub fn set_verification_key(env: Env, vk: VerificationKey) {
        let admin: Address = env
            .storage()
            .instance()
            .get(&ADMIN)
            .expect("contract is not initialized");
        admin.require_auth();
        env.storage().instance().set(&VERIFICATION_KEY, &vk);
        log!(&env, "Verification key updated by admin");
    }

    /// Set a new model hash. Only callable by admin.
    pub fn set_model_hash(env: Env, model_hash: Bytes) {
        let admin: Address = env
            .storage()
            .instance()
            .get(&ADMIN)
            .expect("contract is not initialized");
        admin.require_auth();
        env.storage().instance().set(&MODEL_HASH, &model_hash);
        log!(&env, "Model hash updated by admin");
    }

    /// Set a new admin address. Only callable by current admin.
    pub fn set_admin(env: Env, new_admin: Address) {
        let admin: Address = env
            .storage()
            .instance()
            .get(&ADMIN)
            .expect("contract is not initialized");
        admin.require_auth();
        env.storage().instance().set(&ADMIN, &new_admin);
        log!(&env, "Admin updated");
    }

    /// Set the pause flag. Only callable by admin.
    pub fn set_pause(env: Env, paused: bool) {
        let admin: Address = env
            .storage()
            .instance()
            .get(&ADMIN)
            .expect("contract is not initialized");
        admin.require_auth();
        env.storage().instance().set(&PAUSED, &paused);
        log!(&env, "Pause flag set to {}", paused);
    }

    /// Get the current admin address.
    pub fn get_admin(env: Env) -> Address {
        env.storage()
            .instance()
            .get(&ADMIN)
            .expect("contract is not initialized")
    }

    /// Get the current pause state.
    pub fn is_paused(env: Env) -> bool {
        env.storage().instance().get(&PAUSED).unwrap_or(false)
    }
}

#[cfg(test)]
mod test_utils {
    use super::*;
    use soroban_sdk::Env;

    /// Create a dummy verification key for testing.
    /// Uses the G1 generator point (1, 2) which is valid.
    /// num_ic specifies the number of IC points (must be >= 3 for model_hash, input_hash, output).
    pub fn create_dummy_vk(env: &Env, num_ic: u32) -> VerificationKey {
        let g1_bytes: [u8; 64] = [
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 2,
        ];
        let g2_bytes = [0u8; 128];
        let _g1 = Bn254G1Affine::from_array(env, &g1_bytes);
        let _g2 = Bn254G2Affine::from_array(env, &g2_bytes);

        let mut ic = Vec::new(env);
        for _ in 0..num_ic {
            ic.push_back(Bytes::from_slice(env, &g1_bytes));
        }

        VerificationKey {
            alpha: Bytes::from_slice(env, &g1_bytes),
            beta: Bytes::from_slice(env, &g2_bytes),
            gamma: Bytes::from_slice(env, &g2_bytes),
            delta: Bytes::from_slice(env, &g2_bytes),
            ic,
        }
    }

    /// Create dummy proof components for testing.
    pub fn dummy_proof(env: &Env) -> (Bytes, Bytes, Bytes) {
        let proof_a = Bytes::from_slice(env, &[0u8; 64]);
        let proof_b = Bytes::from_slice(env, &[0u8; 128]);
        let proof_c = Bytes::from_slice(env, &[0u8; 64]);
        (proof_a, proof_b, proof_c)
    }
}

#[cfg(test)]
mod test {
    use super::*;
    use soroban_sdk::testutils::Address as _;
    use soroban_sdk::Env;
    use test_utils::create_dummy_vk;

    #[test]
    fn test_initialize() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);
        let admin = Address::generate(&env);
        let model_hash = Bytes::from_slice(&env, &[1u8; 32]);
        let vk = create_dummy_vk(&env, 4); // 4 IC points for model_hash, input_hash, output
        env.mock_all_auths();
        client.initialize(&admin, &model_hash, &vk);
    }

    #[test]
    #[should_panic(expected = "contract is already initialized")]
    fn test_double_initialize() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);
        let admin = Address::generate(&env);
        let model_hash = Bytes::from_slice(&env, &[1u8; 32]);
        let vk = create_dummy_vk(&env, 4);
        env.mock_all_auths();
        client.initialize(&admin, &model_hash, &vk);
        client.initialize(&admin, &model_hash, &vk);
    }
}

#[cfg(test)]
mod test_guards {
    use super::*;
    use soroban_sdk::testutils::Address as _;
    use soroban_sdk::Env;
    use test_utils::create_dummy_vk;

    fn setup(env: &Env) -> ZkmlVerifierContractClient<'_> {
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(env, &contract_id);
        let admin = Address::generate(env);
        let model_hash = Bytes::from_slice(env, &[3u8; 32]);
        let vk = create_dummy_vk(env, 5);
        env.mock_all_auths();
        client.initialize(&admin, &model_hash, &vk);
        client
    }

    #[test]
    fn verify_malformed_proof_a() {
        let env = Env::default();
        let client = setup(&env);

        let proof_a = Bytes::from_slice(&env, &[0u8; 8]); // Wrong length
        let proof_b = Bytes::from_slice(&env, &[0u8; 128]);
        let proof_c = Bytes::from_slice(&env, &[0u8; 64]);
        let public_inputs = Bytes::from_slice(&env, &[7u8; 80]);

        let result = client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        assert_eq!(result, Err(Ok(VerificationError::MalformedProofA)));
    }

    #[test]
    fn verify_malformed_proof_b() {
        let env = Env::default();
        let client = setup(&env);

        // Use valid G1 generator point for proof_a and proof_c
        let g1_bytes: [u8; 64] = [
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 2,
        ];
        let proof_a = Bytes::from_slice(&env, &g1_bytes);
        let proof_b = Bytes::from_slice(&env, &[0u8; 8]); // Wrong length
        let proof_c = Bytes::from_slice(&env, &g1_bytes);
        let public_inputs = Bytes::from_slice(&env, &[7u8; 80]);

        let result = client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        // Should fail due to malformed proof_b (wrong length)
        assert!(result.is_err());
    }

    #[test]
    fn verify_malformed_proof_c() {
        let env = Env::default();
        let client = setup(&env);

        // Use valid G1 generator point for proof_a
        let g1_bytes: [u8; 64] = [
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 2,
        ];
        let proof_a = Bytes::from_slice(&env, &g1_bytes);
        let proof_b = Bytes::from_slice(&env, &[0u8; 128]);
        let proof_c = Bytes::from_slice(&env, &[0u8; 8]); // Wrong length
        let public_inputs = Bytes::from_slice(&env, &[7u8; 80]);
        let result = client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        // Should fail due to malformed proof_c (wrong length)
        assert!(result.is_err());
    }

    #[test]
    fn verify_public_inputs_too_short() {
        let env = Env::default();
        let client = setup(&env);

        let proof_a = Bytes::from_slice(&env, &[0u8; 64]);
        let proof_b = Bytes::from_slice(&env, &[0u8; 128]);
        let proof_c = Bytes::from_slice(&env, &[0u8; 64]);
        let public_inputs = Bytes::from_slice(&env, &[7u8; 32]); // Too short

        let result = client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        assert_eq!(result, Err(Ok(VerificationError::PublicInputsTooShort)));
    }

    #[test]
    fn verify_invalid_output_length() {
        let env = Env::default();
        let client = setup(&env);

        let proof_a = Bytes::from_slice(&env, &[0u8; 64]);
        let proof_b = Bytes::from_slice(&env, &[0u8; 128]);
        let proof_c = Bytes::from_slice(&env, &[0u8; 64]);
        // 32+32+8+8+8 = 88 bytes - extra 8 bytes after parsing all fields
        let public_inputs = Bytes::from_slice(&env, &[7u8; 88]);

        let result = client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        assert_eq!(result, Err(Ok(VerificationError::InvalidPublicInputLength)));
    }

    #[test]
    fn verify_vk_length_mismatch() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);

        // Initialize with VK that has 6 IC points
        let admin = Address::generate(&env);
        let model_hash = Bytes::from_slice(&env, &[3u8; 32]);
        let vk = create_dummy_vk(&env, 6);
        env.mock_all_auths();
        client.initialize(&admin, &model_hash, &vk);

        // Provide public inputs for single output + class_label (4 scalars: model_hash, input_hash, output, class_label)
        // This requires 5 IC points, but VK has 6
        let proof_a = Bytes::from_slice(&env, &[0u8; 64]);
        let proof_b = Bytes::from_slice(&env, &[0u8; 128]);
        let proof_c = Bytes::from_slice(&env, &[0u8; 64]);
        let public_inputs = Bytes::from_slice(&env, &[3u8; 80]);

        let result = client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        assert_eq!(
            result,
            Err(Ok(VerificationError::VerificationKeyLengthMismatch))
        );
    }

    #[test]
    fn verify_multi_scalar_output() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);

        // Initialize with VK that has 5 IC points for single output + class_label (4 scalars)
        let admin = Address::generate(&env);
        let model_hash = Bytes::from_slice(&env, &[3u8; 32]);
        let vk = create_dummy_vk(&env, 5); // ic[0], ic[1], ic[2], ic[3], ic[4]
        env.mock_all_auths();
        client.initialize(&admin, &model_hash, &vk);

        // Provide public inputs for single output + class_label: 32+32+8+8 = 80 bytes
        let proof_a = Bytes::from_slice(&env, &[0u8; 64]);
        let proof_b = Bytes::from_slice(&env, &[0u8; 128]);
        let proof_c = Bytes::from_slice(&env, &[0u8; 64]);
        let public_inputs = Bytes::from_slice(&env, &[3u8; 80]);

        // Should not fail due to length mismatch
        let result = client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        // The important thing is it doesn't return VerificationKeyLengthMismatch
        if let Err(Ok(VerificationError::VerificationKeyLengthMismatch)) = result {
            panic!(
                "Should not fail with VerificationKeyLengthMismatch for valid single output + class_label"
            );
        }
    }

    #[test]
    fn verify_wrong_model_hash() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);

        // Initialize with model hash [3u8; 32]
        let admin = Address::generate(&env);
        let model_hash = Bytes::from_slice(&env, &[3u8; 32]);
        let vk = create_dummy_vk(&env, 5);
        env.mock_all_auths();
        client.initialize(&admin, &model_hash, &vk);

        // Try to verify with different model hash [5u8; 32]
        let proof_a = Bytes::from_slice(&env, &[0u8; 64]);
        let proof_b = Bytes::from_slice(&env, &[0u8; 128]);
        let proof_c = Bytes::from_slice(&env, &[0u8; 64]);
        let public_inputs = Bytes::from_slice(&env, &[5u8; 80]); // 32+32+8+8 = 80 bytes for single output + class_label

        let result = client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        assert_eq!(result, Err(Ok(VerificationError::VerificationFailed)));
    }

    #[test]
    fn verify_replay_attack_prevented() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);

        // Initialize with model hash [3u8; 32]
        let admin = Address::generate(&env);
        let model_hash = Bytes::from_slice(&env, &[3u8; 32]);
        let vk = create_dummy_vk(&env, 5);
        env.mock_all_auths();
        client.initialize(&admin, &model_hash, &vk);

        // First verification should succeed (or fail with verification error, but not ProofAlreadyUsed)
        let proof_a = Bytes::from_slice(&env, &[0u8; 64]);
        let proof_b = Bytes::from_slice(&env, &[0u8; 128]);
        let proof_c = Bytes::from_slice(&env, &[0u8; 64]);
        let public_inputs = Bytes::from_slice(&env, &[3u8; 80]); // 32+32+8+8 = 80 bytes (model_hash + input_hash + output + class_label)

        let first_result =
            client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        // First attempt should not return ProofAlreadyUsed
        if let Err(Ok(VerificationError::ProofAlreadyUsed)) = first_result {
            panic!("First verification should not return ProofAlreadyUsed");
        }

        // Second verification with identical inputs should return ProofAlreadyUsed
        let second_result =
            client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        assert_eq!(second_result, Err(Ok(VerificationError::ProofAlreadyUsed)));
    }

    #[test]
    fn verify_distinct_inputs_independent() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);

        // Initialize with model hash [3u8; 32]
        let admin = Address::generate(&env);
        let model_hash = Bytes::from_slice(&env, &[3u8; 32]);
        let vk = create_dummy_vk(&env, 4);
        env.mock_all_auths();
        client.initialize(&admin, &model_hash, &vk);

        let proof_a = Bytes::from_slice(&env, &[0u8; 64]);
        let proof_b = Bytes::from_slice(&env, &[0u8; 128]);
        let proof_c = Bytes::from_slice(&env, &[0u8; 64]);

        // First verification with input_hash [3u8; 32]
        let public_inputs_1 = Bytes::from_slice(&env, &[3u8; 72]); // model_hash [3u8; 32], input_hash [3u8; 32], output [3u8; 8]
        let first_result =
            client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs_1);
        // First attempt should not return ProofAlreadyUsed
        if let Err(Ok(VerificationError::ProofAlreadyUsed)) = first_result {
            panic!("First verification should not return ProofAlreadyUsed");
        }

        // Second verification with different input_hash [4u8; 32] should not return ProofAlreadyUsed
        let mut public_inputs_2_bytes = [3u8; 72];
        public_inputs_2_bytes[32..64].copy_from_slice(&[4u8; 32]); // Change input_hash bytes
        let public_inputs_2 = Bytes::from_slice(&env, &public_inputs_2_bytes);
        let second_result =
            client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs_2);
        // Should not return ProofAlreadyUsed since input_hash is different
        if let Err(Ok(VerificationError::ProofAlreadyUsed)) = second_result {
            panic!("Verification with different input_hash should not return ProofAlreadyUsed");
        }
    }

    #[test]
    fn verify_distinct_outputs_independent() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);

        // Initialize with model hash [3u8; 32]
        let admin = Address::generate(&env);
        let model_hash = Bytes::from_slice(&env, &[3u8; 32]);
        let vk = create_dummy_vk(&env, 4);
        env.mock_all_auths();
        client.initialize(&admin, &model_hash, &vk);

        let proof_a = Bytes::from_slice(&env, &[0u8; 64]);
        let proof_b = Bytes::from_slice(&env, &[0u8; 128]);
        let proof_c = Bytes::from_slice(&env, &[0u8; 64]);

        // First verification with output [3u8; 8]
        let public_inputs_1 = Bytes::from_slice(&env, &[3u8; 72]); // model_hash [3u8; 32], input_hash [3u8; 32], output [3u8; 8]
        let first_result =
            client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs_1);
        // First attempt should not return ProofAlreadyUsed
        if let Err(Ok(VerificationError::ProofAlreadyUsed)) = first_result {
            panic!("First verification should not return ProofAlreadyUsed");
        }

        // Second verification with different output [4u8; 8] should not return ProofAlreadyUsed
        let mut public_inputs_2_bytes = [3u8; 72];
        public_inputs_2_bytes[64..72].copy_from_slice(&[4u8; 8]); // Change output bytes
        let public_inputs_2 = Bytes::from_slice(&env, &public_inputs_2_bytes);
        let second_result =
            client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs_2);
        // Should not return ProofAlreadyUsed since output is different
        if let Err(Ok(VerificationError::ProofAlreadyUsed)) = second_result {
            panic!("Verification with different output should not return ProofAlreadyUsed");
        }
    }
}

#[cfg(test)]
mod test_poseidon_cross_check {
    use super::*;
    use soroban_sdk::Env;

    #[test]
    fn verify_before_initialize_returns_error() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);
        let proof_a = Bytes::from_slice(&env, &[0u8; 64]);
        let proof_b = Bytes::from_slice(&env, &[0u8; 128]);
        let proof_c = Bytes::from_slice(&env, &[0u8; 64]);
        let public_inputs = Bytes::from_slice(&env, &[7u8; 80]); // 32+32+8+8 = 80 bytes

        let result = client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        assert_eq!(result, Err(Ok(VerificationError::ContractNotInitialized)));
    }

    #[test]
    fn model_commitment_is_reproducible() {
        let env = Env::default();
        let test_data = [1u8, 2u8, 3u8];
        let commitment = Bytes::from_slice(&env, &test_data);
        assert_eq!(commitment, Bytes::from_slice(&env, &test_data));
    }
}

#[cfg(test)]
mod test_admin_auth {
    use super::*;
    use soroban_sdk::testutils::Address as _;
    use soroban_sdk::Env;
    use test_utils::{create_dummy_vk, dummy_proof};

    fn setup_with_admin(env: &Env) -> (ZkmlVerifierContractClient<'_>, Address) {
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(env, &contract_id);
        let admin = Address::generate(env);
        let model_hash = Bytes::from_slice(env, &[3u8; 32]);
        let vk = create_dummy_vk(env, 5);
        env.mock_all_auths();
        client.initialize(&admin, &model_hash, &vk);
        (client, admin)
    }

    #[test]
    fn initialize_without_admin_auth_fails() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);
        let admin = Address::generate(&env);
        let model_hash = Bytes::from_slice(&env, &[1u8; 32]);
        let vk = create_dummy_vk(&env, 4);

        // Try to initialize without mocking auth - should fail
        let result = client.try_initialize(&admin, &model_hash, &vk);
        assert!(result.is_err());
    }

    #[test]
    fn initialize_with_admin_auth_succeeds() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);
        let admin = Address::generate(&env);
        let model_hash = Bytes::from_slice(&env, &[1u8; 32]);
        let vk = create_dummy_vk(&env, 4);

        // Mock auth for admin
        env.mock_all_auths();
        client.initialize(&admin, &model_hash, &vk);

        // Verify admin was stored
        let stored_admin = client.get_admin();
        assert_eq!(stored_admin, admin);
    }

    #[test]
    fn set_verification_key_authorized_succeeds() {
        let env = Env::default();
        let (client, _admin) = setup_with_admin(&env);
        let new_vk = create_dummy_vk(&env, 5);

        // Mock auth for admin
        env.mock_all_auths();
        client.set_verification_key(&new_vk);

        // Verify contract state is still accessible
        let stored_model_hash = client.get_model_hash();
        assert_eq!(stored_model_hash, Bytes::from_slice(&env, &[3u8; 32]));
    }

    #[test]
    fn set_model_hash_authorized_succeeds() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);
        let admin = Address::generate(&env);
        let model_hash = Bytes::from_slice(&env, &[3u8; 32]);
        let vk = create_dummy_vk(&env, 5);

        // Initialize with auth
        env.mock_all_auths();
        client.initialize(&admin, &model_hash, &vk);

        let new_model_hash = Bytes::from_slice(&env, &[5u8; 32]);

        // Mock auth for admin again
        env.mock_all_auths();
        client.set_model_hash(&new_model_hash);

        // Verify model hash was updated
        let stored_model_hash = client.get_model_hash();
        assert_eq!(stored_model_hash, new_model_hash);
    }

    #[test]
    fn set_model_hash_unauthorized_fails() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);
        let admin = Address::generate(&env);
        let model_hash = Bytes::from_slice(&env, &[3u8; 32]);
        let vk = create_dummy_vk(&env, 5);

        // Initialize with auth
        env.mock_all_auths();
        client.initialize(&admin, &model_hash, &vk);

        let (proof_a, proof_b, proof_c) = dummy_proof(&env);
        let public_inputs = Bytes::from_slice(&env, &[5u8; 80]);
        let result = client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        assert_eq!(result, Err(Ok(VerificationError::VerificationFailed)));
        assert_eq!(client.get_verification_count(), 0);
    }

    #[test]
    fn set_admin_authorized_succeeds() {
        let env = Env::default();
        let (client, _admin) = setup_with_admin(&env);
        let _new_admin = Address::generate(&env);

        let (proof_a, proof_b, proof_c) = dummy_proof(&env);
        let public_inputs = Bytes::from_slice(&env, &[5u8; 80]);

        let result = client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        assert_eq!(result, Err(Ok(VerificationError::VerificationFailed)));
    }

    #[test]
    fn contract_state_accessible_after_key_rotation() {
        let env = Env::default();
        let (client, _admin) = setup_with_admin(&env);

        // Rotate verification key
        let new_vk = create_dummy_vk(&env, 4);
        env.mock_all_auths();
        client.set_verification_key(&new_vk);

        // Verify that contract state is still accessible after rotation
        let stored_model_hash = client.get_model_hash();
        assert_eq!(stored_model_hash, Bytes::from_slice(&env, &[3u8; 32]));
    }

    #[test]
    fn get_admin_returns_stored_admin() {
        let env = Env::default();
        let (client, admin) = setup_with_admin(&env);

        let retrieved_admin = client.get_admin();
        assert_eq!(retrieved_admin, admin);
    }

    #[test]
    fn is_paused_returns_correct_state() {
        let env = Env::default();
        let (client, _admin) = setup_with_admin(&env);

        // Initially not paused
        assert!(!client.is_paused());

        // Pause
        env.mock_all_auths();
        client.set_pause(&true);
        assert!(client.is_paused());

        // Unpause
        client.set_pause(&false);
        assert!(!client.is_paused());
    }
}

#[cfg(test)]
mod test_verified_event {
    use super::*;
    use soroban_sdk::testutils::Events;
    use soroban_sdk::IntoVal;

    #[test]
    fn verify_emits_verified_event_with_model_hash_and_output() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());

        let model_hash = Bytes::from_slice(&env, &[0xabu8; 32]);
        let output = Bytes::from_slice(&env, &[1, 2, 3, 4, 5, 6, 7, 8]);
        let record = InferenceRecord {
            model_hash: model_hash.clone(),
            output: output.clone(),
            class_label: 1,
            verified_at: 1234,
        };

        env.as_contract(&contract_id, || {
            ZkmlVerifierContract::emit_verified_event(&env, &record);
        });

        assert_eq!(
            env.events().all(),
            vec![
                &env,
                (
                    contract_id.clone(),
                    (symbol_short!("verified"), model_hash.clone()).into_val(&env),
                    (1234u32, output.clone()).into_val(&env),
                ),
            ]
        );
    }
}

#[cfg(test)]
mod test_budget {
    extern crate std;
    use super::*;
    use soroban_sdk::crypto::bn254::{Bn254Fr, Bn254G1Affine};
    use soroban_sdk::testutils::Address as _;
    use soroban_sdk::{vec as sdk_vec, BytesN, Env};
    use std::println;

    /// BN254 G1 generator (1, 2) – valid non-infinity point.
    const G1_GEN: [u8; 64] = [
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 2,
    ];

    /// Valid non-infinity BN254 G2 point, sourced from the soroban-env-host
    /// test suite (g1_pairing_hardcoded).  Serialized in Soroban/Ethereum
    /// format: x_imaginary(32) || x_real(32) || y_imaginary(32) || y_real(32),
    /// each component big-endian.
    const G2_GEN: [u8; 128] = [
        0x1f, 0xb1, 0x9b, 0xb4, 0x76, 0xf6, 0xb9, 0xe4, 0x4e, 0x2a, 0x32, 0x23, 0x4d, 0xa8, 0x21,
        0x2f, 0x61, 0xcd, 0x63, 0x91, 0x93, 0x54, 0xbc, 0x06, 0xae, 0xf3, 0x1e, 0x3c, 0xfa, 0xff,
        0x3e, 0xbc, 0x22, 0x60, 0x68, 0x45, 0xff, 0x18, 0x67, 0x93, 0x91, 0x4e, 0x03, 0xe2, 0x1d,
        0xf5, 0x44, 0xc3, 0x4f, 0xfe, 0x2f, 0x2f, 0x35, 0x04, 0xde, 0x8a, 0x79, 0xd9, 0x15, 0x9e,
        0xca, 0x2d, 0x98, 0xd9, 0x2b, 0xd3, 0x68, 0xe2, 0x83, 0x81, 0xe8, 0xec, 0xcb, 0x5f, 0xa8,
        0x1f, 0xc2, 0x6c, 0xf3, 0xf0, 0x48, 0xee, 0xa9, 0xab, 0xfd, 0xd8, 0x5d, 0x7e, 0xd3, 0xab,
        0x36, 0x98, 0xd6, 0x3e, 0x4f, 0x90, 0x2f, 0xe0, 0x2e, 0x47, 0x88, 0x75, 0x07, 0xad, 0xf0,
        0xff, 0x17, 0x43, 0xcb, 0xac, 0x6b, 0xa2, 0x91, 0xe6, 0x6f, 0x59, 0xbe, 0x6b, 0xd7, 0x63,
        0x95, 0x0b, 0xb1, 0x60, 0x41, 0xa0, 0xa8, 0x5e,
    ];

    /// Build a scalar Bn254Fr from a small u64 value (big-endian 32-byte encoding).
    fn fr_from_u64(env: &Env, val: u64) -> Bn254Fr {
        let mut buf = [0u8; 32];
        let be = val.to_be_bytes();
        buf[24..32].copy_from_slice(&be);
        Bn254Fr::from_bytes(BytesN::from_array(env, &buf))
    }

    /// Construct a valid accept-path verification key with non-degenerate points.
    ///
    /// All G2 points (beta, gamma, delta) are a known-good BN254 G2 point
    /// from the soroban-env-host test suite.  All IC entries are the BN254
    /// G1 generator.
    ///
    /// 5 IC points: IC[0] + model·IC[1] + input·IC[2] + output·IC[3] + class_label·IC[4]
    pub fn create_accept_fixture_vk(env: &Env) -> VerificationKey {
        VerificationKey {
            alpha: Bytes::from_slice(env, &G1_GEN),
            beta: Bytes::from_slice(env, &G2_GEN),
            gamma: Bytes::from_slice(env, &G2_GEN),
            delta: Bytes::from_slice(env, &G2_GEN),
            ic: sdk_vec![
                env,
                Bytes::from_slice(env, &G1_GEN),
                Bytes::from_slice(env, &G1_GEN),
                Bytes::from_slice(env, &G1_GEN),
                Bytes::from_slice(env, &G1_GEN),
                Bytes::from_slice(env, &G1_GEN),
            ],
        }
    }

    /// Compute a proof that satisfies the Groth16 pairing check.
    ///
    /// Given the VK and public-input scalars (model, input, output, class_label),
    /// this uses BN254 host functions to compute:
    ///   L  = IC[0] + model·IC[1] + input·IC[2] + output·IC[3] + class_label·IC[4]
    ///   C  = −L
    ///
    /// Then the pairing:
    ///   e(−A, B) · e(α, β) · e(L, γ) · e(C, δ)
    /// = e(−G1 + G1 + L − L, G2)
    /// = e(O, G2) = 1  ✓
    pub fn compute_valid_proof(
        env: &Env,
        vk: &VerificationKey,
        model_scalar: u64,
        input_scalar: u64,
        output_scalar: u64,
        class_label_scalar: u64,
    ) -> (Bytes, Bytes, Bytes) {
        let bn254 = env.crypto().bn254();

        // Deserialize IC[0] as the starting point for L
        let ic0_bytes = vk.ic.get(0).unwrap();
        let mut ic0_arr = [0u8; 64];
        ic0_bytes.copy_into_slice(&mut ic0_arr);
        let mut l = Bn254G1Affine::from_array(env, &ic0_arr);

        // L += model_scalar * IC[1]
        let ic1_bytes = vk.ic.get(1).unwrap();
        let mut ic1_arr = [0u8; 64];
        ic1_bytes.copy_into_slice(&mut ic1_arr);
        let ic1 = Bn254G1Affine::from_array(env, &ic1_arr);
        let term1 = bn254.g1_mul(&ic1, &fr_from_u64(env, model_scalar));
        l = bn254.g1_add(&l, &term1);

        // L += input_scalar * IC[2]
        let ic2_bytes = vk.ic.get(2).unwrap();
        let mut ic2_arr = [0u8; 64];
        ic2_bytes.copy_into_slice(&mut ic2_arr);
        let ic2 = Bn254G1Affine::from_array(env, &ic2_arr);
        let term2 = bn254.g1_mul(&ic2, &fr_from_u64(env, input_scalar));
        l = bn254.g1_add(&l, &term2);

        // L += output_scalar * IC[3]
        let ic3_bytes = vk.ic.get(3).unwrap();
        let mut ic3_arr = [0u8; 64];
        ic3_bytes.copy_into_slice(&mut ic3_arr);
        let ic3 = Bn254G1Affine::from_array(env, &ic3_arr);
        let term3 = bn254.g1_mul(&ic3, &fr_from_u64(env, output_scalar));
        l = bn254.g1_add(&l, &term3);

        // L += class_label_scalar * IC[4]
        let ic4_bytes = vk.ic.get(4).unwrap();
        let mut ic4_arr = [0u8; 64];
        ic4_bytes.copy_into_slice(&mut ic4_arr);
        let ic4 = Bn254G1Affine::from_array(env, &ic4_arr);
        let term4 = bn254.g1_mul(&ic4, &fr_from_u64(env, class_label_scalar));
        l = bn254.g1_add(&l, &term4);

        // C = −L  (proof_c)
        let c = -l;

        // A = G1 generator, B = G2 point
        let proof_a = Bytes::from_slice(env, &G1_GEN);
        let proof_b = Bytes::from_slice(env, &G2_GEN);
        let proof_c = Bytes::from_slice(env, &c.to_array());

        (proof_a, proof_b, proof_c)
    }

    #[test]
    fn test_verifier_accept_path_and_resource_budget() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);

        // --- Public-input scalars: model=3, input=5, output=42, class_label=7. ---
        // bytes_to_fr interprets input as little-endian, so we encode
        // each scalar as [val, 0, 0, ..., 0] (32 bytes LE for model/input,
        // 8 bytes LE for output/class_label i64).
        let model_le = {
            let mut b = [0u8; 32];
            b[0] = 3;
            b
        };
        let input_le = {
            let mut b = [0u8; 32];
            b[0] = 5;
            b
        };
        // Output is a single i64 scalar in LE (8 bytes)
        let output_le = {
            let mut b = [0u8; 8];
            b[0] = 42;
            b
        };
        // Class label is a single i64 scalar in LE (8 bytes)
        let class_label_le = {
            let mut b = [0u8; 8];
            b[0] = 7;
            b
        };

        // --- VK with non-degenerate G2 and non-zero IC ---
        let model_hash = Bytes::from_slice(&env, &model_le);
        let vk = create_accept_fixture_vk(&env);
        let admin = Address::generate(&env);
        env.mock_all_auths();
        client.initialize(&admin, &model_hash, &vk);

        // --- Proof that genuinely satisfies the pairing ---
        let (proof_a, proof_b, proof_c) = compute_valid_proof(&env, &vk, 3, 5, 42, 7);

        // Public inputs: model(32) + input(32) + output(8) + class_label(8) = 80 bytes
        // Parsed as: 1 model + 1 input + 1 output + 1 class_label = 4 scalars → IC[0..4]
        let mut public_inputs_vec = [0u8; 80];
        public_inputs_vec[0..32].copy_from_slice(&model_le);
        public_inputs_vec[32..64].copy_from_slice(&input_le);
        public_inputs_vec[64..72].copy_from_slice(&output_le);
        public_inputs_vec[72..80].copy_from_slice(&class_label_le);
        let public_inputs = Bytes::from_slice(&env, &public_inputs_vec);

        // --- Measure resource budget ---
        env.cost_estimate().budget().reset_default();

        let result = client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        assert_eq!(result, Ok(Ok(())));

        let cpu = env.cost_estimate().budget().cpu_instruction_cost();
        let mem = env.cost_estimate().budget().memory_bytes_cost();

        println!("\n=== Verifier Resource Budget Harness Report ===");
        println!("CPU Instructions : {}", cpu);
        println!("Memory Bytes     : {}", mem);
        println!("===============================================\n");

        // Regression threshold assertion: fail if cost regresses sharply.
        // Thresholds are generous to avoid flaky tests; the point is to
        // catch large regressions, not to be tight.
        const MAX_CPU_THRESHOLD: u64 = 50_000_000;
        const MAX_MEM_THRESHOLD: u64 = 10_000_000;

        assert!(
            cpu <= MAX_CPU_THRESHOLD,
            "Verifier CPU instruction cost regressed sharply: got {}, threshold {}",
            cpu,
            MAX_CPU_THRESHOLD
        );
        assert!(
            mem <= MAX_MEM_THRESHOLD,
            "Verifier Memory bytes cost regressed sharply: got {}, threshold {}",
            mem,
            MAX_MEM_THRESHOLD
        );
    }
}

/// The contract side of RISC Zero receipt verification.
///
/// The value these tests protect is agreement: the contract recomputes a claim
/// digest with the Soroban host's SHA-256, while the prover computes it with
/// `sha2`. If the two ever disagree by one byte, every proof fails on chain
/// with nothing to point at. So the expected digests here are the ones
/// `zkml-common` produces, and `crates/zkml-prover/tests/risc0_digests.rs`
/// separately pins those against `risc0-zkvm` itself.
#[cfg(test)]
mod test_risc0_receipts {
    use super::*;
    use soroban_sdk::testutils::Address as _;
    use soroban_sdk::Bytes;

    /// A journal the guest could really have committed.
    fn journal_bytes(env: &Env) -> Bytes {
        let journal = zkml_common::journal::JournalV1 {
            model_kind: zkml_common::journal::ModelKind::LogisticRegression,
            model_hash: [0x11; 32],
            input_hash: [0x22; 32],
            output: 34865,
            class_label: 1,
        };
        Bytes::from_slice(env, &journal.encode())
    }

    fn setup(env: &Env) -> (ZkmlVerifierContractClient<'_>, Address) {
        env.mock_all_auths();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(env, &contract_id);
        let admin = Address::generate(env);
        let model_hash = Bytes::from_slice(env, &[0x11; 32]);
        let vk = crate::test_utils::create_dummy_vk(env, 5);
        client.initialize(&admin, &model_hash, &vk);
        (client, admin)
    }

    fn config(env: &Env) -> Risc0Config {
        Risc0Config {
            image_id: Bytes::from_slice(env, &[0xaa; 32]),
            control_root: Bytes::from_slice(env, &[0xbb; 32]),
            bn254_control_id: Bytes::from_slice(env, &[0xcc; 32]),
            selector: Bytes::from_slice(env, &[0x73, 0xc4, 0x57, 0xba]),
        }
    }

    #[test]
    fn the_contract_and_the_prover_agree_on_the_claim_digest() {
        let env = Env::default();
        let (client, _admin) = setup(&env);

        let image_id = [0xaa_u8; 32];
        let journal = journal_bytes(&env);

        // What the contract computes, with the host's SHA-256.
        let on_chain = client.claim_digest(&Bytes::from_slice(&env, &image_id), &journal);

        // What the shared arithmetic computes off chain, with sha2.
        let mut raw = [0u8; zkml_common::journal::JOURNAL_V1_LEN];
        journal.copy_into_slice(&mut raw);
        let off_chain = zkml_common::risc0::receipt_claim_ok_digest(
            zkml_common::risc0::Sha2Hasher,
            &image_id,
            &raw,
        );

        assert_eq!(
            on_chain,
            Bytes::from_slice(&env, &off_chain),
            "the host SHA-256 and sha2 must produce the same claim digest"
        );
    }

    #[test]
    fn the_claim_digest_binds_the_journal_and_the_image_id() {
        let env = Env::default();
        let (client, _admin) = setup(&env);
        let image_id = Bytes::from_slice(&env, &[0xaa; 32]);
        let journal = journal_bytes(&env);
        let base = client.claim_digest(&image_id, &journal);

        // One different byte in the journal.
        let mut raw = [0u8; zkml_common::journal::JOURNAL_V1_LEN];
        journal.copy_into_slice(&mut raw);
        raw[72] ^= 0x01; // the output field
        let other_journal = Bytes::from_slice(&env, &raw);
        assert_ne!(base, client.claim_digest(&image_id, &other_journal));

        // One different byte in the image id.
        let mut id = [0xaa_u8; 32];
        id[0] ^= 0x01;
        assert_ne!(
            base,
            client.claim_digest(&Bytes::from_slice(&env, &id), &journal)
        );
    }

    #[test]
    fn the_risc0_config_round_trips() {
        let env = Env::default();
        let (client, _admin) = setup(&env);
        let cfg = config(&env);
        client.set_risc0_config(&cfg);

        let stored = client.get_risc0_config();
        assert_eq!(stored.image_id, cfg.image_id);
        assert_eq!(stored.control_root, cfg.control_root);
        assert_eq!(stored.bn254_control_id, cfg.bn254_control_id);
        assert_eq!(stored.selector, cfg.selector);
    }

    #[test]
    #[should_panic(expected = "risc0 config fields have the wrong length")]
    fn a_short_image_id_is_rejected() {
        let env = Env::default();
        let (client, _admin) = setup(&env);
        let mut cfg = config(&env);
        cfg.image_id = Bytes::from_slice(&env, &[0xaa; 31]);
        client.set_risc0_config(&cfg);
    }

    #[test]
    #[should_panic(expected = "risc0 config has not been set")]
    fn reading_the_config_before_setting_it_says_so() {
        let env = Env::default();
        let (client, _admin) = setup(&env);
        client.get_risc0_config();
    }
}

/// The golden fixture: a real receipt, verified on chain.
///
/// Everything else in this file tests the contract against values chosen to
/// exercise a path. This tests it against a proof that a real zkVM run really
/// produced, with the verifying key the pinned RISC Zero version really uses.
/// It is the only test here that would notice if the digest arithmetic, the
/// byte orders, or the key were subtly wrong, because every one of those
/// produces a valid-looking failure rather than an error.
///
/// The fixture in `testdata/` took 22 minutes of CPU to make. Regenerate it
/// with:
///
/// ```text
/// RISC0_DEV_MODE=0 cargo test -p zkml-prover --features groth16 \
///     --test groth16_bundle real_groth16 -- --ignored
/// cargo run -p zkml-prover --features zkvm -- export-vk --format json \
///     -o crates/zkml-verifier/testdata/risc0_vk.json
/// ```
#[cfg(test)]
mod test_golden_receipt {
    use super::*;
    use soroban_sdk::testutils::Address as _;
    use soroban_sdk::Bytes;

    fn hex_to_vec(hex: &str) -> std::vec::Vec<u8> {
        assert!(hex.len() % 2 == 0, "hex must have an even length");
        (0..hex.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).expect("valid hex"))
            .collect()
    }

    fn read(name: &str) -> serde_json::Value {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("testdata")
            .join(name);
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
        serde_json::from_str(&text).expect("valid json")
    }

    fn bytes(env: &Env, hex: &str) -> Bytes {
        Bytes::from_slice(env, &hex_to_vec(hex))
    }

    /// The contract, initialised for the model the fixture's journal names and
    /// configured for the guest that produced it.
    fn setup(env: &Env) -> (ZkmlVerifierContractClient<'_>, Bytes, Bytes) {
        env.mock_all_auths();
        let bundle = read("groth16_bundle.json");
        let vk_json = read("risc0_vk.json");

        let seal = bytes(env, bundle["seal"].as_str().unwrap());
        let journal = bytes(env, bundle["journal"].as_str().unwrap());

        // The model hash the journal carries. Registering anything else must
        // make verification fail, which a later test checks.
        let journal_raw = hex_to_vec(bundle["journal"].as_str().unwrap());
        let decoded = zkml_common::journal::JournalV1::decode(&journal_raw).expect("journal");
        let model_hash = Bytes::from_slice(env, &decoded.model_hash);

        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(env, &contract_id);
        let admin = Address::generate(env);
        let route_b_vk = crate::test_utils::create_dummy_vk(env, 5);
        client.initialize(&admin, &model_hash, &route_b_vk);

        // The image id comes from the bundle, not from whatever guest this
        // checkout builds: a bundle is self-describing, and the fixture was
        // produced by an earlier guest.
        client.set_risc0_config(&Risc0Config {
            image_id: bytes(env, bundle["image_id"].as_str().unwrap()),
            control_root: bytes(env, vk_json["control_root"].as_str().unwrap()),
            bn254_control_id: bytes(env, vk_json["bn254_control_id"].as_str().unwrap()),
            selector: bytes(env, vk_json["selector"].as_str().unwrap()),
        });

        let vk = &vk_json["vk"];
        let mut ic = Vec::new(env);
        for point in vk["ic"].as_array().unwrap() {
            ic.push_back(bytes(env, point.as_str().unwrap()));
        }
        client.set_risc0_vk(&VerificationKey {
            alpha: bytes(env, vk["alpha"].as_str().unwrap()),
            beta: bytes(env, vk["beta"].as_str().unwrap()),
            gamma: bytes(env, vk["gamma"].as_str().unwrap()),
            delta: bytes(env, vk["delta"].as_str().unwrap()),
            ic,
        });

        (client, seal, journal)
    }

    #[test]
    fn a_real_receipt_verifies_on_chain() {
        let env = Env::default();
        let (client, seal, journal) = setup(&env);

        client.verify_receipt(&seal, &journal);

        // And the result it recorded is the one the journal carries.
        let record = client.get_result();
        assert_eq!(record.class_label, 1);
        assert_eq!(client.get_verification_count(), 1);
    }

    /// What a real receipt costs on chain.
    ///
    /// This is the number that decides whether the design is usable at all:
    /// Soroban caps a transaction at 100 million CPU instructions, and the
    /// pairing check alone was already 29 million before receipts existed.
    /// Verifying a receipt adds the claim digest, which is eight SHA-256 host
    /// calls, and one more scalar multiplication than the native-circuit path.
    ///
    /// Measured on the golden fixture, so the number is the cost of a
    /// verification that actually succeeds, not of a cheap early rejection.
    #[test]
    fn a_real_receipt_fits_in_the_transaction_budget() {
        use std::println;

        let env = Env::default();
        let (client, seal, journal) = setup(&env);

        env.cost_estimate().budget().reset_default();
        client.verify_receipt(&seal, &journal);

        let cpu = env.cost_estimate().budget().cpu_instruction_cost();
        let mem = env.cost_estimate().budget().memory_bytes_cost();

        println!("\n=== verify_receipt on a real bundle ===");
        println!("CPU instructions : {}", cpu);
        println!("Memory bytes     : {}", mem);
        println!("=======================================\n");

        // The network limit, which is what actually matters. If this ever
        // fails, receipts cannot be verified on chain at all and the design
        // needs rethinking, not a looser threshold.
        const SOROBAN_CPU_LIMIT: u64 = 100_000_000;
        assert!(
            cpu < SOROBAN_CPU_LIMIT,
            "verify_receipt costs {cpu} instructions and the network allows {SOROBAN_CPU_LIMIT}"
        );

        // A regression guard, generous on purpose: it exists to catch a change
        // that doubles the cost, not to police small movements.
        const MAX_CPU: u64 = 60_000_000;
        const MAX_MEM: u64 = 12_000_000;
        assert!(cpu <= MAX_CPU, "CPU cost regressed: {cpu} over {MAX_CPU}");
        assert!(
            mem <= MAX_MEM,
            "memory cost regressed: {mem} over {MAX_MEM}"
        );
    }

    #[test]
    fn the_same_receipt_cannot_be_used_twice() {
        let env = Env::default();
        let (client, seal, journal) = setup(&env);

        client.verify_receipt(&seal, &journal);
        assert_eq!(
            client.try_verify_receipt(&seal, &journal),
            Err(Ok(VerificationError::ProofAlreadyUsed))
        );
    }

    #[test]
    fn one_flipped_byte_of_the_journal_is_rejected() {
        let env = Env::default();
        let (client, seal, journal) = setup(&env);

        let mut raw = [0u8; zkml_common::journal::JOURNAL_V1_LEN];
        journal.copy_into_slice(&mut raw);
        raw[72] ^= 0x01; // the output field
        let tampered = Bytes::from_slice(&env, &raw);

        // The journal reaches the proof only through the claim digest, so this
        // has to fail the pairing rather than any cheaper check.
        assert_eq!(
            client.try_verify_receipt(&seal, &tampered),
            Err(Ok(VerificationError::VerificationFailed))
        );
    }

    #[test]
    fn one_flipped_byte_of_the_seal_is_rejected() {
        let env = Env::default();
        let (client, seal, journal) = setup(&env);

        let mut raw = std::vec![0u8; seal.len() as usize];
        seal.copy_into_slice(&mut raw);
        raw[100] ^= 0x01; // inside the B point
        let tampered = Bytes::from_slice(&env, &raw);

        // Not a contract error: flipping a byte inside a curve point usually
        // takes it off the curve, and the BN254 host functions trap on a point
        // they cannot parse rather than returning. The transaction fails either
        // way; only the diagnostic differs. Validating points up front would
        // cost gas on every honest verification to improve the message on a
        // dishonest one, which is the wrong trade.
        assert_eq!(
            client.try_verify_receipt(&tampered, &journal),
            Err(Err(soroban_sdk::InvokeError::Abort)),
            "a corrupted proof point traps in the host"
        );
    }

    #[test]
    fn a_seal_from_another_risc0_version_is_rejected_by_its_selector() {
        let env = Env::default();
        let (client, seal, journal) = setup(&env);

        let mut raw = std::vec![0u8; seal.len() as usize];
        seal.copy_into_slice(&mut raw);
        raw[0] ^= 0xff;
        let tampered = Bytes::from_slice(&env, &raw);

        // Caught before the pairing, and with an error that names the cause.
        assert_eq!(
            client.try_verify_receipt(&tampered, &journal),
            Err(Ok(VerificationError::UnknownSelector))
        );
    }

    #[test]
    fn a_truncated_seal_is_rejected() {
        let env = Env::default();
        let (client, seal, journal) = setup(&env);
        let short = seal.slice(0..259);
        assert_eq!(
            client.try_verify_receipt(&short, &journal),
            Err(Ok(VerificationError::MalformedSeal))
        );
    }

    #[test]
    fn a_journal_of_the_wrong_length_is_rejected() {
        let env = Env::default();
        let (client, seal, journal) = setup(&env);
        let short = journal.slice(0..95);
        assert_eq!(
            client.try_verify_receipt(&seal, &short),
            Err(Ok(VerificationError::MalformedJournal))
        );
    }

    #[test]
    fn a_receipt_for_another_model_is_rejected() {
        let env = Env::default();
        env.mock_all_auths();
        let (client, seal, journal) = setup(&env);

        // Re-register the contract for a different model.
        client.set_model_hash(&Bytes::from_slice(&env, &[0x99; 32]));
        assert_eq!(
            client.try_verify_receipt(&seal, &journal),
            Err(Ok(VerificationError::VerificationFailed))
        );
    }

    #[test]
    fn verifying_before_configuring_says_so() {
        let env = Env::default();
        env.mock_all_auths();
        let bundle = read("groth16_bundle.json");
        let seal = bytes(&env, bundle["seal"].as_str().unwrap());
        let journal = bytes(&env, bundle["journal"].as_str().unwrap());

        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);
        let admin = Address::generate(&env);
        let vk = crate::test_utils::create_dummy_vk(&env, 5);
        client.initialize(&admin, &Bytes::from_slice(&env, &[0x11; 32]), &vk);

        assert_eq!(
            client.try_verify_receipt(&seal, &journal),
            Err(Ok(VerificationError::Risc0NotConfigured))
        );
    }
}
