//! # zkml-verifier
//!
//! Soroban smart contract that verifies Groth16 proofs of ML inference.
//!
//! This contract provides on-chain verification of zero-knowledge proofs
//! generated by the off-chain prover. It leverages the BN254 elliptic curve
//! host functions introduced in Stellar Protocol 25 (X-Ray) via CAP-0074,
//! and uses Poseidon hash commitments from CAP-0075 .
//!
//! # Contract Interface
//!
//! - `initialize`: Register the verification key and model commitment.
//! - `verify_inference`: Accept a Groth16 proof and public inputs, verify
//!   correctness, and record the result on-chain.
//! - `get_result`: Query the last verified inference result for a model.

#![no_std]

use soroban_sdk::{contract, contractimpl, contracttype, log, symbol_short, Bytes, Env, Symbol};

// ---------------------------------------------------------------------------
// Storage keys
// ---------------------------------------------------------------------------

const MODEL_HASH: Symbol = symbol_short!("mdl_hash");
const LAST_RESULT: Symbol = symbol_short!("lst_res");
const INITIALIZED: Symbol = symbol_short!("init");

// ---------------------------------------------------------------------------
// Data types
// ---------------------------------------------------------------------------

/// On-chain record of a verified inference result.
#[contracttype]
#[derive(Clone, Debug)]
pub struct InferenceRecord {
    /// Poseidon commitment to the model that produced this result.
    pub model_hash: Bytes,
    /// The inference output value.
    pub output: Bytes,
    /// Ledger sequence number at verification time.
    pub verified_at: u32,
}

// ---------------------------------------------------------------------------
// Contract
// ---------------------------------------------------------------------------

#[contract]
pub struct ZkmlVerifierContract;

#[contractimpl]
impl ZkmlVerifierContract {
    /// Initialize the contract with a model commitment.
    ///
    /// Must be called exactly once before any verification calls.
    pub fn initialize(env: Env, model_hash: Bytes) {
        if env.storage().instance().has(&INITIALIZED) {
            panic!("contract is already initialized");
        }

        env.storage().instance().set(&MODEL_HASH, &model_hash);
        env.storage().instance().set(&INITIALIZED, &true);

        log!(&env, "ZKML verifier initialized with model commitment");
    }

    /// Verify a Groth16 proof of ML inference.
    ///
    /// # Arguments
    ///
    /// * `proof_a` - The `A` point of the Groth16 proof (serialized).
    /// * `proof_b` - The `B` point of the Groth16 proof (serialized).
    /// * `proof_c` - The `C` point of the Groth16 proof (serialized).
    /// * `public_inputs` - Serialized public inputs (model hash, input hash, output).
    ///
    /// # Returns
    ///
    /// `true` if the proof is valid, `false` otherwise.
    pub fn verify_inference(
        env: Env,
        proof_a: Bytes,
        proof_b: Bytes,
        proof_c: Bytes,
        public_inputs: Bytes,
    ) -> bool {
        if !env.storage().instance().has(&INITIALIZED) {
            panic!("contract is not initialized");
        }

        // TODO: Call BN254 host functions (CAP-0074) to perform
        // the Groth16 pairing check:
        //
        //   e(A, B) == e(alpha, beta) * e(sum(pub_i * vk_i), gamma) * e(C, delta)
        //
        // For now, this is a placeholder that logs the attempt.
        log!(
            &env,
            "Groth16 verification requested — BN254 host function integration pending"
        );

        // Placeholder: in production, this will be replaced by the actual
        // pairing check result.
        let _proof_a = proof_a;
        let _proof_b = proof_b;
        let _proof_c = proof_c;
        let _public_inputs = public_inputs;

        // Record result on success (placeholder logic).
        let stored_hash: Bytes = env.storage().instance().get(&MODEL_HASH).unwrap();
        let record = InferenceRecord {
            model_hash: stored_hash,
            output: Bytes::new(&env),
            verified_at: env.ledger().sequence(),
        };
        env.storage().instance().set(&LAST_RESULT, &record);

        true
    }

    /// Retrieve the last verified inference result.
    pub fn get_result(env: Env) -> InferenceRecord {
        env.storage()
            .instance()
            .get(&LAST_RESULT)
            .expect("no inference result has been recorded yet")
    }
}

#[cfg(test)]
mod test {
    use super::*;
    use soroban_sdk::Env;

    #[test]
    fn test_initialize() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);

        let model_hash = Bytes::from_slice(&env, &[1u8; 32]);
        client.initialize(&model_hash);
    }

    #[test]
    #[should_panic(expected = "contract is already initialized")]
    fn test_double_initialize() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);

        let model_hash = Bytes::from_slice(&env, &[1u8; 32]);
        client.initialize(&model_hash);
        client.initialize(&model_hash);
    }
}
