//! # zkml-verifier
//!
//! Soroban smart contract that verifies Groth16 proofs of ML inference.
//!
//! This contract provides on-chain verification of zero-knowledge proofs
//! generated by the off-chain prover. It leverages the BN254 elliptic curve
//! host functions introduced in Stellar Protocol 25 (X-Ray) via CAP-0074,
//! and uses Poseidon hash commitments from CAP-0075.
//!
//! # Contract Interface
//!
//! - `initialize`: Register the model commitment.
//! - `verify_inference`: Accept a Groth16 proof and public inputs, verify
//!   correctness, record the result, and emit an event.
//! - `get_result`: Query the last verified inference result.
//! - `get_model_hash`: Query the registered model commitment.
//! - `get_verification_count`: Query how many proofs have been verified.

#![no_std]

extern crate alloc;

use soroban_sdk::{
    contract, contracterror, contractimpl, contracttype, log, symbol_short, Bytes, Env, Symbol, Vec,
};

// Storage keys
const MODEL_HASH: Symbol = symbol_short!("mdl_hash");
const LAST_RESULT: Symbol = symbol_short!("lst_res");
const INITIALIZED: Symbol = symbol_short!("init");
const VERIFY_CNT: Symbol = symbol_short!("vrf_cnt");
const VERIFICATION_KEY: Symbol = symbol_short!("vk_key");

/// Contract interface version, bumped on breaking interface changes.
pub const VERSION: u32 = 1;

/// Rejection / Verification Errors
#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
pub enum VerifierError {
    NotInitialized = 1,
    AlreadyInitialized = 2,
    InvalidModelHash = 3,
    InvalidInputsLength = 4,
    InvalidProofLength = 5,
}

/// On-chain representation of BN254 Groth16 verification key.
#[contracttype]
#[derive(Clone, Debug)]
pub struct VerificationKey {
    /// G1 point alpha (64 bytes)
    pub alpha: Bytes,
    /// G2 point beta (128 bytes)
    pub beta: Bytes,
    /// G2 point gamma (128 bytes)
    pub gamma: Bytes,
    /// G2 point delta (128 bytes)
    pub delta: Bytes,
    /// IC points array (each G1 point, 64 bytes)
    pub ic: Vec<Bytes>,
}

/// On-chain record of a verified inference result.
#[contracttype]
#[derive(Clone, Debug)]
pub struct InferenceRecord {
    /// Poseidon commitment to the model that produced this result.
    pub model_hash: Bytes,
    /// The inference output value.
    pub output: Bytes,
    /// Ledger sequence number at verification time.
    pub verified_at: u32,
}

#[contract]
pub struct ZkmlVerifierContract;

#[contractimpl]
impl ZkmlVerifierContract {
    /// Initialize the contract with a model commitment and verification key. Call exactly once.
    pub fn initialize(env: Env, model_hash: Bytes, vk: VerificationKey) {
        if env.storage().instance().has(&INITIALIZED) {
            panic!("contract is already initialized");
        }
        env.storage().instance().set(&MODEL_HASH, &model_hash);
        env.storage().instance().set(&VERIFICATION_KEY, &vk);
        env.storage().instance().set(&VERIFY_CNT, &0u32);
        env.storage().instance().set(&INITIALIZED, &true);
        log!(
            &env,
            "ZKML verifier initialized with model commitment and VK"
        );
    }

    /// Verify a Groth16 proof of ML inference.
    ///
    /// `public_inputs` is the concatenation of the 32-byte model commitment,
    /// the 32-byte input commitment, and the output bytes.
    pub fn verify_inference(
        env: Env,
        proof_a: Bytes,
        proof_b: Bytes,
        proof_c: Bytes,
        public_inputs: Bytes,
    ) -> Result<bool, VerifierError> {
        if !env.storage().instance().has(&INITIALIZED) {
            return Err(VerifierError::NotInitialized);
        }

        // Check lengths
        if proof_a.len() != 64 || proof_b.len() != 128 || proof_c.len() != 64 {
            return Err(VerifierError::InvalidProofLength);
        }

        // Validate public inputs
        let stored_model_hash = env
            .storage()
            .instance()
            .get::<_, Bytes>(&MODEL_HASH)
            .ok_or(VerifierError::NotInitialized)?;

        if public_inputs.len() < 64 {
            return Err(VerifierError::InvalidInputsLength);
        }
        if !public_inputs.len().is_multiple_of(32) {
            return Err(VerifierError::InvalidInputsLength);
        }

        let model_hash = public_inputs.slice(0..32);
        if model_hash != stored_model_hash {
            return Err(VerifierError::InvalidModelHash);
        }

        let output = public_inputs.slice(64..public_inputs.len());

        // TODO: Implement actual Groth16 verification
        // This is a placeholder that will be implemented in a separate PR
        // For now, just return true after model hash binding check

        // Save result
        let record = InferenceRecord {
            model_hash,
            output,
            verified_at: env.ledger().sequence(),
        };
        env.storage().instance().set(&LAST_RESULT, &record);

        let count: u32 = env.storage().instance().get(&VERIFY_CNT).unwrap_or(0);
        env.storage().instance().set(&VERIFY_CNT, &(count + 1));

        #[allow(deprecated)]
        env.events()
            .publish((symbol_short!("verified"),), record.verified_at);

        Ok(true)
    }

    /// Retrieve the last verified inference result.
    pub fn get_result(env: Env) -> InferenceRecord {
        env.storage()
            .instance()
            .get(&LAST_RESULT)
            .expect("no inference result has been recorded yet")
    }

    /// Retrieve the registered model commitment.
    pub fn get_model_hash(env: Env) -> Bytes {
        env.storage()
            .instance()
            .get(&MODEL_HASH)
            .expect("contract is not initialized")
    }

    /// Retrieve the number of verified proofs so far.
    pub fn get_verification_count(env: Env) -> u32 {
        env.storage().instance().get(&VERIFY_CNT).unwrap_or(0)
    }

    /// Return the contract interface version.
    pub fn version(_env: Env) -> u32 {
        VERSION
    }
}

#[cfg(test)]
mod test {
    use super::*;
    use soroban_sdk::Env;

    fn get_mock_vk(env: &Env) -> VerificationKey {
        VerificationKey {
            alpha: Bytes::from_slice(env, &[0u8; 64]),
            beta: Bytes::from_slice(env, &[0u8; 128]),
            gamma: Bytes::from_slice(env, &[0u8; 128]),
            delta: Bytes::from_slice(env, &[0u8; 128]),
            ic: soroban_sdk::Vec::new(env),
        }
    }

    #[test]
    fn test_initialize() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);
        let model_hash = Bytes::from_slice(&env, &[1u8; 32]);
        let vk = get_mock_vk(&env);
        client.initialize(&model_hash, &vk);
    }

    #[test]
    #[should_panic(expected = "contract is already initialized")]
    fn test_double_initialize() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);
        let model_hash = Bytes::from_slice(&env, &[1u8; 32]);
        let vk = get_mock_vk(&env);
        client.initialize(&model_hash, &vk);
        client.initialize(&model_hash, &vk);
    }

    #[test]
    fn verify_with_wrong_model_hash_fails() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);
        let model_hash = Bytes::from_slice(&env, &[3u8; 32]);
        let vk = get_mock_vk(&env);
        client.initialize(&model_hash, &vk);

        let proof_a = Bytes::from_slice(&env, &[0u8; 64]);
        let proof_b = Bytes::from_slice(&env, &[0u8; 128]);
        let proof_c = Bytes::from_slice(&env, &[0u8; 64]);
        // Public inputs with different model_hash (first 32 bytes)
        let mut public_inputs = [7u8; 96];
        public_inputs[0] = 99; // Different model_hash
        let public_inputs = Bytes::from_slice(&env, &public_inputs);

        let res = client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        assert_eq!(res.err().unwrap().unwrap(), VerifierError::InvalidModelHash);
    }
}

#[cfg(test)]
mod test_guards {
    use super::*;
    use soroban_sdk::Env;

    #[test]
    fn verify_before_initialize_fails() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);
        let proof = Bytes::from_slice(&env, &[0u8; 64]);
        let public_inputs = Bytes::from_slice(&env, &[7u8; 96]);
        let res = client.try_verify_inference(&proof, &proof, &proof, &public_inputs);

        assert_eq!(res.err().unwrap().unwrap(), VerifierError::NotInitialized);
    }
}

#[cfg(test)]
mod test_poseidon_cross_check {
    use super::*;
    use soroban_sdk::Env;

    #[test]
    fn model_commitment_is_reproducible() {
        let env = Env::default();
        let test_data = [1u8, 2u8, 3u8];
        let commitment = Bytes::from_slice(&env, &test_data);
        assert_eq!(commitment, Bytes::from_slice(&env, &test_data));
    }
}
